foreach(name IN ITEMS headless controls native audio-device preview-async inspector live-paint)
  add_executable(genesis-${name} "${GENESIS_ROOT}/build-windows/generated/${name}.c")
  target_include_directories(genesis-${name} PRIVATE "${CMAKE_SOURCE_DIR}/runtime")
  target_link_libraries(genesis-${name} PRIVATE air_rt)
  set_target_properties(genesis-${name} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
endforeach()
add_executable(genesis-worker-wrapper "${GENESIS_ROOT}/tests/worker_wrapper.c")
set_target_properties(genesis-worker-wrapper PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")

add_executable(genesis-ui-pixels "${CMAKE_SOURCE_DIR}/tests/stdlib/ui_pixels.c")
target_include_directories(genesis-ui-pixels PRIVATE "${CMAKE_SOURCE_DIR}/runtime")
set_target_properties(genesis-ui-pixels PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
